/**
 * Dossier core — the dossier workflow's light query/persistence half.
 *
 * 拆分约定（架构走查候选 2）：本模块是「轻查询核」，单源承载档案的持久化
 * （persist/load/peek/delete/list，含 #55 质量视图与旧档案覆盖估算）、开局门闩
 * 降质判定（dossierGateNotice）与查询期纯函数 lookups（场景块渲染/词面检索/
 * 场景查找）。依赖白名单只有 node:fs/promises、node:path、config、pathSafety
 * 与同目录轻模块（schema / coverageGaps / sceneLookup）——**不准**静态引入
 * storyService（→ jsdom/pdf-lib 解析链）、aiService、annex、prompts：重生成链
 * 全部在 `./dossierGenerate.js`，只有生成期路由该背那条链。
 *
 * 查询期消费方（roomService / supplementService / scriptContext 等）一律动态
 * import 本模块（保持既有动态风格）；`./storyDossierService.ts` 是兼容两半的
 * re-export 门面——静态引它 = 连带生成器重依赖链，轻消费方别走门面。
 *
 * A dossier is a structured story digest (scenes/clues/npcs with machine-
 * readable gates + per-scene narrative text) pre-generated by an LLM from the
 * full story text, replacing per-turn embedding retrieval for dossier rooms.
 * Reads are TTL-cached in memory (mirrors graphStore memory cache pattern).
 *
 * Path safety: dossier file names come from a whitelist-filtered script id
 * (mirrors vectorStore.indexPath); the route layer asserts the id first.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { DOSSIER_DATA_DIR } from '../../config.js'
import { resolveFileInDir } from '../../utils/pathSafety.js'
import {
  parseDossierJson,
  sanitizeScriptId,
  DOSSIER_MIN_COVERAGE_PCT,
  type StoryDossier,
} from './schema.js'
import { findScene as findSceneImpl } from './sceneLookup.js'
import { deleteGaps, GAPS_VERSION, type SceneCoverage } from './coverageGaps.js'

/** TTL for in-memory dossier cache (ms). */
const CACHE_TTL_MS = 60_000

const memoryCache = new Map<string, { loadedAt: number; dossier: StoryDossier }>()

function cacheKey(userId: number, scriptId: string): string {
  return `${userId}:${scriptId}`
}

/** Per-user dossier dir (never built from the raw script id). */
function userDir(userId: number): string {
  return path.join(DOSSIER_DATA_DIR, String(userId))
}

/** Resolve a script id to a file path: whitelist-sanitize to a safe file name
 * then boundary-check the result inside the user dir (白名单 + resolve 边界
 * 双保险——路径穿越不可达). The route layer asserts/sanitizes first. */
function dossierFile(userId: number, scriptId: string): string {
  const safe = sanitizeScriptId(scriptId)
  return resolveFileInDir(userDir(userId), `${safe}.json`, 'dossier file')
}

async function ensureDir(userId: number): Promise<string> {
  await fs.mkdir(userDir(userId), { recursive: true })
  return userDir(userId)
}

/* ═══════════════════ Persistence ═══════════════════ */

export async function persist(userId: number, dossier: StoryDossier): Promise<void> {
  await ensureDir(userId)
  const file = dossierFile(userId, dossier.scriptId)
  await fs.writeFile(file, JSON.stringify(dossier, null, 2), 'utf-8')
  memoryCache.set(cacheKey(userId, dossier.scriptId), { loadedAt: Date.now(), dossier })
}

export async function deleteDossier(userId: number, scriptId: string): Promise<boolean> {
  memoryCache.delete(cacheKey(userId, scriptId))
  // annex 是重模块（pdf-lib/aiService/storyService）——轻核静态图不带它；
  // 删除是冷路径，按仓库既有动态导入风格就地取（执行顺序不变：先清 annex
  // 再清 gaps 再删档案本体）。
  const { deleteAnnex } = await import('./annex.js')
  await deleteAnnex(userId, scriptId)
  await deleteGaps(userId, scriptId)
  try {
    await fs.unlink(dossierFile(userId, scriptId))
    return true
  } catch {
    return false
  }
}

/** Load a dossier from disk (cached). null when missing/unparsable. */
export async function loadDossier(userId: number, scriptId: string): Promise<StoryDossier | null> {
  const key = cacheKey(userId, scriptId)
  const hit = memoryCache.get(key)
  if (hit && Date.now() - hit.loadedAt < CACHE_TTL_MS) return hit.dossier
  try {
    const raw = await fs.readFile(dossierFile(userId, scriptId), 'utf-8')
    const dossier = parseDossierJson(raw)
    if (dossier) {
      memoryCache.set(key, { loadedAt: Date.now(), dossier })
      return dossier
    }
  } catch {
    // missing file → null
  }
  return null
}

/** Synchronous cache-only read (for handlers that cannot await). */
export function peekDossier(userId: number, scriptId: string): StoryDossier | null {
  return memoryCache.get(cacheKey(userId, scriptId))?.dossier ?? null
}

/** 档案清单条目（#55：带生成期质量视图，故事列表/开局门闩据此判定降质）。 */
export interface DossierListItem {
  scriptId: string
  name: string
  sceneCount: number
  generatedAt: number
  /** sceneText 覆盖率（%）：快照直读；旧档案由 .gaps.json 兄弟文件估算。 */
  coveragePct?: number
  /** 降质标记：快照 degraded，或旧档案估算覆盖 < DOSSIER_MIN_COVERAGE_PCT。 */
  degraded?: boolean
  /** 快照中的分节失败数（旧档案估算路径无此值）。 */
  failedBatches?: number
}

/** List a user's generated dossiers (disk scan). */
export async function listDossiers(userId: number): Promise<DossierListItem[]> {
  let entries: string[]
  try {
    entries = await fs.readdir(userDir(userId))
  } catch {
    return []
  }
  const out: DossierListItem[] = []
  for (const f of entries) {
    if (!f.endsWith('.json')) continue
    try {
      const raw = await fs.readFile(path.join(userDir(userId), f), 'utf-8')
      const d = parseDossierJson(raw)
      if (!d) continue
      const item: DossierListItem = {
        scriptId: d.scriptId,
        name: d.storyName,
        sceneCount: d.scenes.length,
        generatedAt: d.generatedAt,
        coveragePct: d.quality?.coveragePct,
        degraded: d.quality?.degraded,
        failedBatches: d.quality?.failedBatches,
      }
      if (d.quality === undefined) {
        // 旧档案（quality 快照引入前）：读同目录兄弟 .gaps.json 估算覆盖。
        // 兄弟文件名源自 readdir 磁盘清单（非请求输入），不引入 keyed fs 读。
        const est = await estimateLegacyCoverage(userDir(userId), f)
        if (est !== undefined) {
          item.coveragePct = est
          item.degraded = est < DOSSIER_MIN_COVERAGE_PCT
        }
      }
      out.push(item)
    } catch {
      // skip unparsable files
    }
  }
  return out.sort((a, b) => b.generatedAt - a.generatedAt)
}

/** 旧档案覆盖估算：兄弟 .gaps.json 的缺口比（100 - gapPct）。仅信当前算法版本
 *  （v1 的 gapPct 系统性偏高，宁放行不误伤）；无明细/损坏 → undefined（不判定）。 */
async function estimateLegacyCoverage(dir: string, dossierFileName: string): Promise<number | undefined> {
  try {
    const gapsPath = path.join(dir, `${dossierFileName.slice(0, -'.json'.length)}.gaps.json`)
    const gaps = JSON.parse(await fs.readFile(gapsPath, 'utf-8')) as { storyChars?: number; gapPct?: number; gapsVersion?: number } | null
    if (!gaps || typeof gaps.storyChars !== 'number' || typeof gaps.gapPct !== 'number') return undefined
    if ((gaps.gapsVersion ?? 1) < GAPS_VERSION) return undefined
    if (gaps.storyChars <= 5_000) return undefined // 小剧本不判降质（与快照口径一致）
    return Math.round((100 - gaps.gapPct) * 10) / 10
  } catch {
    return undefined
  }
}

/* ═══════════════════ 质量门提示（#55 产物期） ═══════════════════ */

/** 降质档案的开局拒绝文案（单源：startRoom / createSoloRoom 经 dossierGateNotice
 *  共用，与「尚未生成档案」的 409 严格分开——缺档案指引生成，残档指引重生成）。 */
function dossierDegradedNoticeText(q: { coveragePct?: number; failedBatches?: number }): string {
  const bits: string[] = []
  if (typeof q.coveragePct === 'number') bits.push(`sceneText 覆盖率仅 ${q.coveragePct}%`)
  if (q.failedBatches) bits.push(`${q.failedBatches} 个分节解析失败`)
  return (
    `档案质量不足（${bits.join('；') || '低覆盖'}）——残档会让 KP 反复查证空转、游玩体验明显变差。` +
    `建议在「我的故事」中重新生成档案后再开局。`
  )
}

/**
 * #55 开局门闩降质判定（**纯函数**）：档案清单里该剧本的降质提示，null = 放行。
 * 输入来自 listDossiers 磁盘扫描（文件名源自 readdir，非请求输入）——门闩的
 * REST 可达链上不出现"以请求 id 为键"的 fs 读；缺档案与无质量数据的旧档案
 * 返回 null（「未生成」由各门闩的既有分支提示，不是降质）。
 */
export function dossierGateNotice(items: DossierListItem[], scriptId: string): string | null {
  const hit = items.find((d) => d.scriptId === scriptId)
  if (!hit || hit.degraded === undefined) return null
  return hit.degraded
    ? dossierDegradedNoticeText({ coveragePct: hit.coveragePct, failedBatches: hit.failedBatches })
    : null
}

/* ═══════════════════ Lookups ═══════════════════ */

export function listScenes(dossier: StoryDossier): { id: string; name: string; description?: string }[] {
  return (dossier.scenes || []).map((s) => ({ id: s.id, name: s.name, description: s.description }))
}

/** 档案落空/覆盖不足时指向查证工具的引导句（单源：三个渲染函数共用）。 */
export const VERIFY_ORIGINAL_HINT = '可用 verify_original 在剧本原文中查证'

/** 覆盖提示行（P26）：仅在"确有缺口"时出声——覆盖完整的场景不打扰 KP。 */
export function coverageHintLine(coverage: SceneCoverage | null | undefined): string {
  if (!coverage || coverage.gapCount <= 0) return ''
  return `原文收录：约 ${coverage.coveragePct}%（另有 ${coverage.gapCount} 段未收录）——需要原文级细节时${VERIFY_ORIGINAL_HINT}，不要凭印象补全。`
}

/** Render a scene's static dossier block (used by buildDossierContext).
 *  传入 coverage 时附一行覆盖提示（P26：让 KP 知道块内可能缺东西）。 */
export function buildSceneBlock(dossier: StoryDossier, sceneNameOrId: string, coverage?: SceneCoverage | null): string {
  const scene = findScene(dossier, sceneNameOrId)
  if (!scene) return ''
  const lines: string[] = []
  lines.push(`场景：${scene.name}`)
  if (scene.description) lines.push(`简介：${scene.description}`)
  if (scene.sceneText) lines.push(`现场描述：\n${scene.sceneText}`)
  if (scene.npcIds?.length) {
    const npcs = (scene.npcIds || [])
      .map((id) => dossier.npcs.find((n) => n.id === id))
      .filter((n): n is StoryDossier['npcs'][number] => !!n)
    if (npcs.length) lines.push(`在场 NPC：${npcs.map((n) => `${n.name}（${n.role ?? '身份不明'}）${n.description ? `：${n.description}` : ''}`).join('；')}`)
  }
  if (scene.hooks?.length) lines.push(`可推进的行动：${scene.hooks.join('；')}`)
  if (scene.clueIds?.length) {
    const clues = (scene.clueIds || [])
      .map((id) => dossier.clues.find((c) => c.id === id))
      .filter((c): c is StoryDossier['clues'][number] => !!c)
    if (clues.length) lines.push(`本场景可获得线索：${clues.map((c) => c.description).join('；')}`)
  }
  const hint = coverageHintLine(coverage)
  if (hint) lines.push(hint)
  return lines.join('\n')
}

/* 查档案落空时的回包文案（P26）：把"档案没有"显式导向原文查证工具——
 * P25 观测到 KP 以档案为完整真源，落空时会直接放弃或凭印象作答。 */

export function renderSceneNotFound(sceneName: string, sceneNames: string[]): string {
  return `剧本中没有「${sceneName}」。可前往的场景：${sceneNames.join('、') || '（无）'}。档案可能不全——${VERIFY_ORIGINAL_HINT}。`
}

export function renderLexicalMiss(query: string): string {
  return `剧本档案中未找到与「${query}」相关的内容。档案可能不全——${VERIFY_ORIGINAL_HINT}。`
}

/* 房间所报场景与档案对不上时的回包文案（#53）：**不**拿别的场景块顶上。
 * 与 renderSceneNotFound 的区别在"谁报错了"——那条是工具查询的名字没命中，
 * 这条是房间场景（KP transition_scene 自由命名）与档案不一致；诊断指向也不同：
 * 先让 KP 用 transition_scene 把场景名纠正到档案口径，再留查证出口。
 * 两条共用同一句引导。
 * ⚠️ 首行的 `【场景归属提示】` 标记是**必需的**：该文本被塞进 `## 当前场景档案`
 * 标题下，而提示词又说那里是"当前所在场景的权威描述"（kpPromptService）——
 * 没有醒目标记时，"未覆盖"会被读成"这就是当前场景的档案"。 */

export function renderSceneUncovered(sceneName: string, sceneNames: string[]): string {
  const name = String(sceneName ?? '').trim()
  if (!name) return ''
  return (
    `【场景归属提示】档案未覆盖当前场景「${name}」。档案中的场景：${sceneNames.join('、') || '（无）'}。` +
    `不要按别的场景推测当前状况——若确认当前实际位于档案中的某场景，用 transition_scene 以档案里的写法更正场景名；` +
    `也可用 scene_list 查看场景清单。需要原文级细节时${VERIFY_ORIGINAL_HINT}。`
  )
}

/**
 * Case-insensitive scene lookup by id/name/exact/contains (longest match wins).
 * 实现单源在 `./sceneLookup.js`（纯函数轻模块）——查询期模块只为这一个查找不该
 * 被重依赖链牵连。保留这层 wrapper 形态：dossierCore 与门面
 * storyDossierService 的 re-export 都从这里出，既有调用方导入路径不变。
 */
export function findScene(dossier: StoryDossier, nameOrId: string): StoryDossier['scenes'][number] | null {
  return findSceneImpl(dossier, nameOrId)
}

/** Lightweight lexical search over scenes/clues/npcs (shared tool primitive). */
export function lexicalSearch(
  dossier: StoryDossier,
  query: string,
  topK: number = 5,
): { kind: 'scene' | 'clue' | 'npc'; name: string; text: string; score: number }[] {
  const q = tokenize(String(query ?? ''))
  if (q.length === 0) return []
  const hits: { kind: 'scene' | 'clue' | 'npc'; name: string; text: string; score: number }[] = []
  for (const s of dossier.scenes || []) {
    const score = scoreText([s.name, s.description, s.sceneText, (s.keywords || []).join(' ')].filter(Boolean).join(' '), q)
    if (score > 0) hits.push({ kind: 'scene', name: s.name, text: s.sceneText.slice(0, 400) || s.description || '', score })
  }
  for (const c of dossier.clues || []) {
    const score = scoreText([c.description, c.location || ''].join(' '), q)
    if (score > 0) hits.push({ kind: 'clue', name: c.description.slice(0, 30), text: c.description, score })
  }
  for (const n of dossier.npcs || []) {
    const score = scoreText([n.name, n.role || '', n.description || '', n.details || ''].join(' '), q)
    if (score > 0) hits.push({ kind: 'npc', name: n.name, text: n.details || n.description || '', score })
  }
  return hits.sort((a, b) => b.score - a.score).slice(0, topK)
}

/** Tokenize Chinese text: CJK chars as unigrams + latin words. */
function tokenize(text: string): string[] {
  const s = String(text ?? '').toLowerCase()
  const cjk = s.match(/[\u4e00-\u9fff]/g) || []
  const words = s.match(/[a-z0-9]+/g) || []
  return [...cjk, ...words].filter((t) => t.length > 0)
}

function scoreText(text: string, queryTerms: string[]): number {
  const body = tokenize(text)
  if (body.length === 0) return 0
  let score = 0
  for (const t of queryTerms) {
    if (body.includes(t)) score += 1
  }
  return score
}
