/**
 * Story dossier service — the dossier workflow's persistence + query core.
 *
 * A dossier is a structured story digest (scenes/clues/npcs with machine-
 * readable gates + per-scene narrative text) pre-generated by an LLM from the
 * full story text, replacing per-turn embedding retrieval for dossier rooms.
 *
 * Responsibilities:
 *  - generate(userId, story): read the story, batch it, call the LLM per batch,
 *    parse + merge into one StoryDossier, persist to DOSSIER_DATA_DIR/<uid>/.
 *  - load/get: TTL-cached reads (mirrors graphStore memory cache pattern).
 *  - query: the dossier workflow's lookups used by the turn pipeline and the
 *    story-lookup tools — listScenes / getSceneBlock (static per-scene text) /
 *    lexicalSearch (tokenized term overlap).
 *
 * The chat path goes through `chatForRag` (aiService) so it inherits protocol
 * dispatch + URL safety + the MOCK_AI script. In MOCK_AI mode the script
 * returns deterministic JSON for dossier prompts (see mockAi.ts), so e2e can
 * run the whole dossier flow without an LLM.
 *
 * Path safety: dossier file names come from a whitelist-filtered script id
 * (mirrors vectorStore.indexPath); the route layer asserts the id first.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { DOSSIER_DATA_DIR } from '../../config.js'
import { readStoryForRag, readStory } from '../../services/storyService.js'
import { chatForRag } from '../../services/aiService.js'
import { resolveFileInDir } from '../../utils/pathSafety.js'
import {
  DOSSIER_BATCH_CHARS,
  DOSSIER_SYSTEM_PROMPT,
  buildDossierPrompt,
  mergeDossierParts,
} from './prompts.js'
import {
  parseDossierJson,
  sanitizeScriptId,
  resolveRefs,
  assessDossier,
  type StoryDossier,
} from './schema.js'
import { persistAnnex, deleteAnnex, runAnnex } from './annex.js'
import { computeCoverageGaps, persistGaps, deleteGaps } from './coverageGaps.js'

/** TTL for in-memory dossier cache (ms). */
const CACHE_TTL_MS = 60_000
/** Max raw story chars fed to the generator overall (safety; ~170k max known). */
const MAX_GENERATE_CHARS = 200_000
/** Max generation batches per story (safety). */
const MAX_BATCHES = 24

export interface GenerateResult {
  ok: boolean
  scriptId?: string
  scenes?: number
  clues?: number
  npcs?: number
  transitions?: number
  events?: number
  truths?: number
  endings?: number
  /** 结构质量告警（不阻断；见 assessDossier）。 */
  warnings?: string[]
  /** 档案 sceneText 覆盖剧本原文比例（%）。 */
  coveragePct?: number
  /** annex（图信息通道）统计；annex 未跑时为 undefined（见 runAnnex）。 */
  annexImages?: number
  annexDrops?: number
  annexFailed?: number
  annexPending?: number
  annexTransitions?: number
  annexClues?: number
  /** coverage gaps（原文覆盖缺口）：gapCount/gapChars/gapPct（明细在 .gaps.json）。 */
  gapCount?: number
  gapChars?: number
  gapPct?: number
  error?: string
}

const memoryCache = new Map<string, { loadedAt: number; dossier: StoryDossier }>()

function cacheKey(userId: number, scriptId: string): string {
  return `${userId}:${scriptId}`
}

/** Per-user dossier dir (never built from the raw script id). */
function userDir(userId: number): string {
  return path.join(DOSSIER_DATA_DIR, String(userId))
}

/** Resolve a script id to a file path: whitelist-sanitize to a safe file name
 * then boundary-check the result inside the user dir (白名单 + resolve 边界
 * 双保险——路径穿越不可达). The route layer asserts/sanitizes first. */
function dossierFile(userId: number, scriptId: string): string {
  const safe = sanitizeScriptId(scriptId)
  return resolveFileInDir(userDir(userId), `${safe}.json`, 'dossier file')
}

async function ensureDir(userId: number): Promise<string> {
  await fs.mkdir(userDir(userId), { recursive: true })
  return userDir(userId)
}

/* ═══════════════════ Generation ═══════════════════ */

/** Split raw story text into sequential sections for batched LLM extraction. */
export function splitStorySections(content: string, batchChars: number = DOSSIER_BATCH_CHARS): string[] {
  const text = String(content ?? '').trim()
  if (!text) return []
  if (text.length <= batchChars) return [text]
  const sections: string[] = []
  let rest = text
  // Prefer splitting at markdown-ish headings / blank-line paragraph gaps.
  while (rest.length > batchChars) {
    const head = rest.slice(0, batchChars)
    const lastBreak = Math.max(head.lastIndexOf('\n\n'), head.lastIndexOf('\n#'), head.lastIndexOf('\n##'), head.lastIndexOf('\n###'))
    const cutAt = lastBreak >= batchChars * 0.5 ? lastBreak : head.length
    sections.push(rest.slice(0, cutAt).trim())
    rest = rest.slice(cutAt).trim()
  }
  if (rest) sections.push(rest)
  return sections
}

/**
 * Generate a dossier for a user's story. `model` overrides settings (mirrors
 * graphStore.indexGraph's extractionModel param). Reads the story text via
 * readStoryForRag (PDF → parsePdfWithOcr). Batches long stories; feeds
 * previously-seen names back for cross-batch consistency.
 */
export async function generateDossier(
  userId: number,
  scriptId: string,
  options: { model?: string; annex?: boolean } = {},
): Promise<GenerateResult> {
  const { model, annex } = options
  if (!scriptId) return { ok: false, error: 'missing scriptId' }

  let raw: { name: string; content: string }
  try {
    raw = await readStoryForRag(userId, scriptId)
  } catch {
    // Fall back to the plain read for txt/md (no OCR needed).
    try {
      raw = await readStory(userId, scriptId)
    } catch {
      return { ok: false, error: 'story not found' }
    }
  }
  const content = (raw?.content || '').trim()
  if (!content) return { ok: false, error: 'story content is empty' }

  const storyText = content.slice(0, MAX_GENERATE_CHARS)
  const sections = splitStorySections(storyText)
  const batches = sections.slice(0, MAX_BATCHES)
  const totalBatches = batches.length

  const seenSceneNames: string[] = []
  const seenNpcNames: string[] = []
  const seenClueDescriptions: string[] = []
  const parsedParts: StoryDossier[] = []
  let lastError = ''
  let batchFailures = 0

  for (let bi = 0; bi < totalBatches; bi++) {
    const prompt = buildDossierPrompt({
      batchIndex: bi,
      storyText: batches[bi],
      seenSceneNames,
      seenNpcNames,
      seenClueDescriptions,
    })
    try {
      // 推理模型偶发把 output budget 耗在 reasoning 上导致 JSON 截断/解析空 → 重试最多 3 次
      let parsed = null
      let res = null
      for (let attempt = 0; attempt < 4 && !parsed; attempt++) {
        res = await chatForRag(userId, {
          messages: [
            { role: 'system', content: DOSSIER_SYSTEM_PROMPT },
            { role: 'user', content: prompt },
          ],
          temperature: 0,
          // schema v2 每节还要输出 transitions/events/relations，推理模型 reasoning 会吃
          // output budget → 8k 偶发截断/解析空（原型实测 5 节挂 3 节）→ 提到 16k
          maxTokens: 16384,
          model,
        })
        parsed = parseDossierJson(stripCodeFence(res?.content || ''))
      }
      if (parsed && parsed.scenes.length + parsed.clues.length + parsed.npcs.length + (parsed.transitions?.length ?? 0) + (parsed.events?.length ?? 0) + (parsed.truths?.length ?? 0) + (parsed.endings?.length ?? 0) > 0) {
        parsedParts.push({
          ...parsed,
          scriptId: parsed.scriptId || scriptId,
          storyName: parsed.storyName || raw.name || scriptId,
          generatedByModel: parsed.generatedByModel || model,
        })
        for (const s of parsed.scenes) if (s.name && !seenSceneNames.includes(s.name)) seenSceneNames.push(s.name)
        for (const n of parsed.npcs) if (n.name && !seenNpcNames.includes(n.name)) seenNpcNames.push(n.name)
        for (const c of parsed.clues) if (c.description && !seenClueDescriptions.includes(c.description)) seenClueDescriptions.push(c.description)
      } else {
        lastError = `batch ${bi + 1}/${totalBatches}: 解析结果为空`
        batchFailures++
      }
    } catch (e) {
      lastError = `batch ${bi + 1}/${totalBatches}: ${e instanceof Error ? e.message : String(e)}`
      batchFailures++
    }
  }

  if (parsedParts.length === 0) {
    return { ok: false, error: lastError || 'dossier generation failed' }
  }

  const merged = mergeDossierParts(parsedParts)
  const resolved = resolveRefs(merged)
  let dossier: StoryDossier = {
    ...resolved,
    scriptId,
    storyName: resolved.storyName || raw.name || scriptId,
    generatedAt: Date.now(),
    generatedByModel: resolved.generatedByModel || model,
  }

  // map annex（P18）：抽图→视觉→铁律 2 筛选→保守合并。annex 失败不阻断档案
  // 生成（warnings 记一笔）；模型守卫/协议守卫错误同样降级为告警。
  let annexNote = ''
  let annexRan = false
  if (annex) {
    try {
      const annexResult = await runAnnex(userId, { scriptId, storyName: dossier.storyName, dossier, model })
      dossier = annexResult.dossier
      await persistAnnex(userId, annexResult.annex)
      annexRan = true
      annexNote = annexResult.annex.note ?? ''
    } catch (e) {
      annexNote = `annex 未运行：${e instanceof Error ? e.message : String(e)}`
    }
  }

  // coverage gaps（P22）：本地计算原文未被 sceneText 覆盖的区间 + 场景锚点，
  // 落盘 .gaps.json（回退定位/质量门用）；失败不阻断生成。
  let gapsRan = false
  try {
    const gaps = computeCoverageGaps(storyText, dossier.scenes)
    await persistGaps(userId, {
      ...gaps,
      scriptId,
      storyName: dossier.storyName,
      generatedAt: Date.now(),
    })
    dossier = { ...dossier, coverageGaps: { count: gaps.gapCount, chars: gaps.gapChars, pct: gaps.gapPct, at: Date.now() } }
    gapsRan = true
  } catch {
    // gaps 失败仅缺失定位明细，不影响档案
  }

  const quality = assessDossier(dossier, storyText.length)
  const warnings: string[] = [...quality.warnings]
  if (annex && annexNote) warnings.push(annexNote)
  if (batchFailures > 0 && parsedParts.length < totalBatches) {
    warnings.push(`有 ${batchFailures} 个分节解析失败，档案只覆盖前 ${parsedParts.length}/${totalBatches} 节——内容不完整`)
  }

  await persist(userId, dossier)
  const result: GenerateResult = {
    ok: true,
    scriptId,
    scenes: dossier.scenes.length,
    clues: dossier.clues.length,
    npcs: dossier.npcs.length,
    transitions: dossier.transitions?.length ?? 0,
    events: dossier.events?.length ?? 0,
    truths: dossier.truths?.length ?? 0,
    endings: dossier.endings?.length ?? 0,
    warnings: warnings.length ? warnings : undefined,
    coveragePct: quality.coveragePct,
  }
  if (annex && annexRan) {
    result.annexImages = quality.annexImages
    result.annexDrops = quality.annexDrops
    result.annexFailed = quality.annexFailed
    result.annexPending = quality.annexPending
    result.annexTransitions = quality.annexTransitions
    result.annexClues = quality.annexClues
  }
  if (gapsRan) {
    result.gapCount = quality.gapCount
    result.gapChars = quality.gapChars
    result.gapPct = quality.gapPct
  }
  return result
}

/** Strip ```json … ``` fences that some models add despite instructions. */
export function stripCodeFence(raw: string): string {
  const s = String(raw ?? '').trim()
  if (!s) return s
  const fenced = s.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (fenced && fenced[1]) return fenced[1].trim()
  return s
}

/* ═══════════════════ Persistence ═══════════════════ */

export async function persist(userId: number, dossier: StoryDossier): Promise<void> {
  await ensureDir(userId)
  const file = dossierFile(userId, dossier.scriptId)
  await fs.writeFile(file, JSON.stringify(dossier, null, 2), 'utf-8')
  memoryCache.set(cacheKey(userId, dossier.scriptId), { loadedAt: Date.now(), dossier })
}

export async function deleteDossier(userId: number, scriptId: string): Promise<boolean> {
  memoryCache.delete(cacheKey(userId, scriptId))
  await deleteAnnex(userId, scriptId)
  await deleteGaps(userId, scriptId)
  try {
    await fs.unlink(dossierFile(userId, scriptId))
    return true
  } catch {
    return false
  }
}

/** Load a dossier from disk (cached). null when missing/unparsable. */
export async function loadDossier(userId: number, scriptId: string): Promise<StoryDossier | null> {
  const key = cacheKey(userId, scriptId)
  const hit = memoryCache.get(key)
  if (hit && Date.now() - hit.loadedAt < CACHE_TTL_MS) return hit.dossier
  try {
    const raw = await fs.readFile(dossierFile(userId, scriptId), 'utf-8')
    const dossier = parseDossierJson(raw)
    if (dossier) {
      memoryCache.set(key, { loadedAt: Date.now(), dossier })
      return dossier
    }
  } catch {
    // missing file → null
  }
  return null
}

/** Synchronous cache-only read (for handlers that cannot await). */
export function peekDossier(userId: number, scriptId: string): StoryDossier | null {
  return memoryCache.get(cacheKey(userId, scriptId))?.dossier ?? null
}

/** List a user's generated dossiers (disk scan). */
export async function listDossiers(userId: number): Promise<{ scriptId: string; name: string; sceneCount: number; generatedAt: number }[]> {
  let entries: string[]
  try {
    entries = await fs.readdir(userDir(userId))
  } catch {
    return []
  }
  const out: { scriptId: string; name: string; sceneCount: number; generatedAt: number }[] = []
  for (const f of entries) {
    if (!f.endsWith('.json')) continue
    try {
      const raw = await fs.readFile(path.join(userDir(userId), f), 'utf-8')
      const d = parseDossierJson(raw)
      if (d) out.push({ scriptId: d.scriptId, name: d.storyName, sceneCount: d.scenes.length, generatedAt: d.generatedAt })
    } catch {
      // skip unparsable files
    }
  }
  return out.sort((a, b) => b.generatedAt - a.generatedAt)
}

/* ═══════════════════ Lookups ═══════════════════ */

export function listScenes(dossier: StoryDossier): { id: string; name: string; description?: string }[] {
  return (dossier.scenes || []).map((s) => ({ id: s.id, name: s.name, description: s.description }))
}

/** Render a scene's static dossier block (used by buildDossierContext). */
export function buildSceneBlock(dossier: StoryDossier, sceneNameOrId: string): string {
  const scene = findScene(dossier, sceneNameOrId)
  if (!scene) return ''
  const lines: string[] = []
  lines.push(`场景：${scene.name}`)
  if (scene.description) lines.push(`简介：${scene.description}`)
  if (scene.sceneText) lines.push(`现场描述：\n${scene.sceneText}`)
  if (scene.npcIds?.length) {
    const npcs = (scene.npcIds || [])
      .map((id) => dossier.npcs.find((n) => n.id === id))
      .filter((n): n is StoryDossier['npcs'][number] => !!n)
    if (npcs.length) lines.push(`在场 NPC：${npcs.map((n) => `${n.name}（${n.role ?? '身份不明'}）${n.description ? `：${n.description}` : ''}`).join('；')}`)
  }
  if (scene.hooks?.length) lines.push(`可推进的行动：${scene.hooks.join('；')}`)
  if (scene.clueIds?.length) {
    const clues = (scene.clueIds || [])
      .map((id) => dossier.clues.find((c) => c.id === id))
      .filter((c): c is StoryDossier['clues'][number] => !!c)
    if (clues.length) lines.push(`本场景可获得线索：${clues.map((c) => c.description).join('；')}`)
  }
  return lines.join('\n')
}

/** Case-insensitive scene lookup by id/name/exact/contains (longest match wins). */
export function findScene(dossier: StoryDossier, nameOrId: string): StoryDossier['scenes'][number] | null {
  const target = String(nameOrId || '').trim().toLowerCase()
  if (!target) return null
  const scenes = dossier.scenes || []
  for (const s of scenes) {
    if (s.id.toLowerCase() === target || s.name.toLowerCase() === target) return s
  }
  let best: StoryDossier['scenes'][number] | null = null
  let bestLen = 0
  for (const s of scenes) {
    const name = s.name.toLowerCase()
    if (name && target.includes(name) && name.length > bestLen) {
      best = s
      bestLen = name.length
    }
  }
  return best
}

/** Lightweight lexical search over scenes/clues/npcs (shared tool primitive). */
export function lexicalSearch(
  dossier: StoryDossier,
  query: string,
  topK: number = 5,
): { kind: 'scene' | 'clue' | 'npc'; name: string; text: string; score: number }[] {
  const q = tokenize(String(query ?? ''))
  if (q.length === 0) return []
  const hits: { kind: 'scene' | 'clue' | 'npc'; name: string; text: string; score: number }[] = []
  for (const s of dossier.scenes || []) {
    const score = scoreText([s.name, s.description, s.sceneText, (s.keywords || []).join(' ')].filter(Boolean).join(' '), q)
    if (score > 0) hits.push({ kind: 'scene', name: s.name, text: s.sceneText.slice(0, 400) || s.description || '', score })
  }
  for (const c of dossier.clues || []) {
    const score = scoreText([c.description, c.location || ''].join(' '), q)
    if (score > 0) hits.push({ kind: 'clue', name: c.description.slice(0, 30), text: c.description, score })
  }
  for (const n of dossier.npcs || []) {
    const score = scoreText([n.name, n.role || '', n.description || '', n.details || ''].join(' '), q)
    if (score > 0) hits.push({ kind: 'npc', name: n.name, text: n.details || n.description || '', score })
  }
  return hits.sort((a, b) => b.score - a.score).slice(0, topK)
}

/** Tokenize Chinese text: CJK chars as unigrams + latin words. */
function tokenize(text: string): string[] {
  const s = String(text ?? '').toLowerCase()
  const cjk = s.match(/[\u4e00-\u9fff]/g) || []
  const words = s.match(/[a-z0-9]+/g) || []
  return [...cjk, ...words].filter((t) => t.length > 0)
}

function scoreText(text: string, queryTerms: string[]): number {
  const body = tokenize(text)
  if (body.length === 0) return 0
  let score = 0
  for (const t of queryTerms) {
    if (body.includes(t)) score += 1
  }
  return score
}
