/**
 * Story dossier service — the dossier workflow's persistence + query core.
 *
 * A dossier is a structured story digest (scenes/clues/npcs with machine-
 * readable gates + per-scene narrative text) pre-generated by an LLM from the
 * full story text, replacing per-turn embedding retrieval for dossier rooms.
 *
 * Responsibilities:
 *  - generate(userId, story): read the story, batch it, call the LLM per batch,
 *    parse + merge into one StoryDossier, persist to DOSSIER_DATA_DIR/<uid>/.
 *  - load/get: TTL-cached reads (mirrors graphStore memory cache pattern).
 *  - query: the dossier workflow's lookups used by the turn pipeline and the
 *    story-lookup tools — listScenes / getSceneBlock (static per-scene text) /
 *    lexicalSearch (tokenized term overlap).
 *
 * The chat path goes through `chatForRag` (aiService) so it inherits protocol
 * dispatch + URL safety + the MOCK_AI script. In MOCK_AI mode the script
 * returns deterministic JSON for dossier prompts (see mockAi.ts), so e2e can
 * run the whole dossier flow without an LLM.
 *
 * Path safety: dossier file names come from a whitelist-filtered script id
 * (mirrors vectorStore.indexPath); the route layer asserts the id first.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { DOSSIER_DATA_DIR } from '../../config.js'
import { readStoryForRag, readStory } from '../../services/storyService.js'
import { chatForRag } from '../../services/aiService.js'
import { resolveFileInDir } from '../../utils/pathSafety.js'
import {
  DOSSIER_BATCH_CHARS,
  DOSSIER_SYSTEM_PROMPT,
  buildDossierPrompt,
  mergeDossierParts,
} from './prompts.js'
import {
  parseDossierJson,
  sanitizeScriptId,
  resolveRefs,
  assessDossier,
  DOSSIER_MIN_COVERAGE_PCT,
  type StoryDossier,
  type DossierQualitySummary,
} from './schema.js'
import { findScene as findSceneImpl } from './sceneLookup.js'
import { persistAnnex, deleteAnnex, runAnnex } from './annex.js'
import { computeCoverageGaps, persistGaps, deleteGaps, GAPS_VERSION, type SceneCoverage } from './coverageGaps.js'

/** TTL for in-memory dossier cache (ms). */
const CACHE_TTL_MS = 60_000
/** Max raw story chars fed to the generator overall (safety; ~170k max known). */
const MAX_GENERATE_CHARS = 200_000
/** Max generation batches per story (safety). */
const MAX_BATCHES = 24
/**
 * #55 生成期重试预算：每节最多 4 次尝试。前两次原额重发（上游偶发 400/503/
 * 空响应），后两次抬 maxTokens（见 DOSSIER_GEN_MAX_TOKENS_ESCALATED）。
 */
const DOSSIER_GEN_ATTEMPTS = 4
/** 单节生成 maxTokens：推理模型 reasoning 吃 output budget，8k 曾致分节解析空（P13 抬到 16k）。 */
const DOSSIER_GEN_MAX_TOKENS = 16384
/**
 * 重试后段抬到的 maxTokens：temp=0 下原样重发近似复现同一截断（#55 实测
 * 生成 A 三节连挂 4 次重发全灭），抬上限是唯一不动提示词/批大小的自愈杠杆；
 * 端点若拒绝更大值会抛 400 → 计入失败，不劣于现状。
 */
const DOSSIER_GEN_MAX_TOKENS_ESCALATED = 32768

export interface GenerateResult {
  ok: boolean
  scriptId?: string
  scenes?: number
  clues?: number
  npcs?: number
  transitions?: number
  events?: number
  truths?: number
  endings?: number
  /** 结构质量告警（不阻断；见 assessDossier）。 */
  warnings?: string[]
  /** 档案 sceneText 覆盖剧本原文比例（%）。 */
  coveragePct?: number
  /**
   * #55 降质标记：低覆盖（< DOSSIER_MIN_COVERAGE_PCT，仅对 >5000 字符剧本）
   * 或分节解析失败。已随档案落盘（quality 快照）——开局门闩据此拒绝开局。
   */
  degraded?: boolean
  /** annex（图信息通道）统计；annex 未跑时为 undefined（见 runAnnex）。 */
  annexImages?: number
  annexDrops?: number
  annexFailed?: number
  annexPending?: number
  annexTransitions?: number
  annexClues?: number
  /** coverage gaps（原文覆盖缺口）：gapCount/gapChars/gapPct（明细在 .gaps.json）。 */
  gapCount?: number
  gapChars?: number
  gapPct?: number
  error?: string
}

const memoryCache = new Map<string, { loadedAt: number; dossier: StoryDossier }>()

function cacheKey(userId: number, scriptId: string): string {
  return `${userId}:${scriptId}`
}

/** Per-user dossier dir (never built from the raw script id). */
function userDir(userId: number): string {
  return path.join(DOSSIER_DATA_DIR, String(userId))
}

/** Resolve a script id to a file path: whitelist-sanitize to a safe file name
 * then boundary-check the result inside the user dir (白名单 + resolve 边界
 * 双保险——路径穿越不可达). The route layer asserts/sanitizes first. */
function dossierFile(userId: number, scriptId: string): string {
  const safe = sanitizeScriptId(scriptId)
  return resolveFileInDir(userDir(userId), `${safe}.json`, 'dossier file')
}

async function ensureDir(userId: number): Promise<string> {
  await fs.mkdir(userDir(userId), { recursive: true })
  return userDir(userId)
}

/* ═══════════════════ Generation ═══════════════════ */

/** Split raw story text into sequential sections for batched LLM extraction. */
export function splitStorySections(content: string, batchChars: number = DOSSIER_BATCH_CHARS): string[] {
  const text = String(content ?? '').trim()
  if (!text) return []
  if (text.length <= batchChars) return [text]
  const sections: string[] = []
  let rest = text
  // Prefer splitting at markdown-ish headings / blank-line paragraph gaps.
  while (rest.length > batchChars) {
    const head = rest.slice(0, batchChars)
    const lastBreak = Math.max(head.lastIndexOf('\n\n'), head.lastIndexOf('\n#'), head.lastIndexOf('\n##'), head.lastIndexOf('\n###'))
    const cutAt = lastBreak >= batchChars * 0.5 ? lastBreak : head.length
    sections.push(rest.slice(0, cutAt).trim())
    rest = rest.slice(cutAt).trim()
  }
  if (rest) sections.push(rest)
  return sections
}

/**
 * Generate a dossier for a user's story. `model` overrides settings. Reads the
 * story text via readStoryForRag (PDF → parsePdfWithOcr). Batches long stories;
 * feeds previously-seen names back for cross-batch consistency.
 */
export async function generateDossier(
  userId: number,
  scriptId: string,
  options: { model?: string; annex?: boolean } = {},
): Promise<GenerateResult> {
  const { model, annex } = options
  if (!scriptId) return { ok: false, error: 'missing scriptId' }

  let raw: { name: string; content: string }
  try {
    raw = await readStoryForRag(userId, scriptId)
  } catch {
    // Fall back to the plain read for txt/md (no OCR needed).
    try {
      raw = await readStory(userId, scriptId)
    } catch {
      return { ok: false, error: 'story not found' }
    }
  }
  const content = (raw?.content || '').trim()
  if (!content) return { ok: false, error: 'story content is empty' }

  const storyText = content.slice(0, MAX_GENERATE_CHARS)
  const sections = splitStorySections(storyText)
  const batches = sections.slice(0, MAX_BATCHES)
  const totalBatches = batches.length

  const seenSceneNames: string[] = []
  const seenNpcNames: string[] = []
  const seenClueDescriptions: string[] = []
  const parsedParts: StoryDossier[] = []
  let lastError = ''
  let batchFailures = 0

  for (let bi = 0; bi < totalBatches; bi++) {
    const prompt = buildDossierPrompt({
      batchIndex: bi,
      storyText: batches[bi],
      seenSceneNames,
      seenNpcNames,
      seenClueDescriptions,
    })
    // #55：同一节内重试——parse 失败与 chatForRag 抛错（上游 400/503/超时）都算
    // 一次失败尝试；后段尝试抬 maxTokens（temp=0 下原样重发自愈不了确定性截断）。
    let parsed: StoryDossier | null = null
    let lastBatchError = ''
    for (let attempt = 0; attempt < DOSSIER_GEN_ATTEMPTS && !parsed; attempt++) {
      try {
        const res = await chatForRag(userId, {
          messages: [
            { role: 'system', content: DOSSIER_SYSTEM_PROMPT },
            { role: 'user', content: prompt },
          ],
          temperature: 0,
          maxTokens: attempt < 2 ? DOSSIER_GEN_MAX_TOKENS : DOSSIER_GEN_MAX_TOKENS_ESCALATED,
          model,
        })
        parsed = parseDossierJson(stripCodeFence(res?.content || ''))
        if (!parsed) lastBatchError = '解析结果为空/无效 JSON'
      } catch (e) {
        lastBatchError = e instanceof Error ? e.message : String(e)
      }
    }
    if (parsed && parsed.scenes.length + parsed.clues.length + parsed.npcs.length + (parsed.transitions?.length ?? 0) + (parsed.events?.length ?? 0) + (parsed.truths?.length ?? 0) + (parsed.endings?.length ?? 0) > 0) {
      parsedParts.push({
        ...parsed,
        scriptId: parsed.scriptId || scriptId,
        storyName: parsed.storyName || raw.name || scriptId,
        generatedByModel: parsed.generatedByModel || model,
      })
      for (const s of parsed.scenes) if (s.name && !seenSceneNames.includes(s.name)) seenSceneNames.push(s.name)
      for (const n of parsed.npcs) if (n.name && !seenNpcNames.includes(n.name)) seenNpcNames.push(n.name)
      for (const c of parsed.clues) if (c.description && !seenClueDescriptions.includes(c.description)) seenClueDescriptions.push(c.description)
    } else {
      lastError = `batch ${bi + 1}/${totalBatches}: ${lastBatchError || '解析结果为空'}`
      batchFailures++
    }
  }

  if (parsedParts.length === 0) {
    return { ok: false, error: lastError || 'dossier generation failed' }
  }

  const merged = mergeDossierParts(parsedParts)
  const resolved = resolveRefs(merged)
  let dossier: StoryDossier = {
    ...resolved,
    scriptId,
    storyName: resolved.storyName || raw.name || scriptId,
    generatedAt: Date.now(),
    generatedByModel: resolved.generatedByModel || model,
  }

  // map annex（P18）：抽图→视觉→铁律 2 筛选→保守合并。annex 失败不阻断档案
  // 生成（warnings 记一笔）；模型守卫/协议守卫错误同样降级为告警。
  let annexNote = ''
  let annexRan = false
  if (annex) {
    try {
      const annexResult = await runAnnex(userId, { scriptId, storyName: dossier.storyName, dossier, model })
      dossier = annexResult.dossier
      await persistAnnex(userId, annexResult.annex)
      annexRan = true
      annexNote = annexResult.annex.note ?? ''
    } catch (e) {
      annexNote = `annex 未运行：${e instanceof Error ? e.message : String(e)}`
    }
  }

  // coverage gaps（P22）：本地计算原文未被 sceneText 覆盖的区间 + 场景锚点，
  // 落盘 .gaps.json（回退定位/质量门用）；失败不阻断生成。
  let gapsRan = false
  try {
    const gaps = computeCoverageGaps(storyText, dossier.scenes)
    await persistGaps(userId, {
      ...gaps,
      scriptId,
      storyName: dossier.storyName,
      generatedAt: Date.now(),
    })
    dossier = { ...dossier, coverageGaps: { count: gaps.gapCount, chars: gaps.gapChars, pct: gaps.gapPct, at: Date.now() } }
    gapsRan = true
  } catch {
    // gaps 失败仅缺失定位明细，不影响档案
  }

  const quality = assessDossier(dossier, storyText.length)
  const warnings: string[] = [...quality.warnings]
  if (annex && annexNote) warnings.push(annexNote)
  if (batchFailures > 0 && parsedParts.length < totalBatches) {
    warnings.push(`有 ${batchFailures} 个分节解析失败，档案只覆盖前 ${parsedParts.length}/${totalBatches} 节——内容不完整`)
  }

  // #55：生成期质量快照随档案落盘——开局门闩（startRoom / createSoloRoom）据此
  // 拒绝残档开局，不再静默放行。分节失败独立于覆盖率计入：小节失败可能拉不低
  // 覆盖率，但档案依旧不完整。
  const degraded = quality.degraded || batchFailures > 0
  const qualitySummary: DossierQualitySummary = {
    coveragePct: quality.coveragePct,
    degraded,
    failedBatches: batchFailures > 0 ? batchFailures : undefined,
    at: Date.now(),
  }
  dossier = { ...dossier, quality: qualitySummary }

  await persist(userId, dossier)
  const result: GenerateResult = {
    ok: true,
    scriptId,
    scenes: dossier.scenes.length,
    clues: dossier.clues.length,
    npcs: dossier.npcs.length,
    transitions: dossier.transitions?.length ?? 0,
    events: dossier.events?.length ?? 0,
    truths: dossier.truths?.length ?? 0,
    endings: dossier.endings?.length ?? 0,
    warnings: warnings.length ? warnings : undefined,
    coveragePct: quality.coveragePct,
    degraded,
  }
  if (annex && annexRan) {
    result.annexImages = quality.annexImages
    result.annexDrops = quality.annexDrops
    result.annexFailed = quality.annexFailed
    result.annexPending = quality.annexPending
    result.annexTransitions = quality.annexTransitions
    result.annexClues = quality.annexClues
  }
  if (gapsRan) {
    result.gapCount = quality.gapCount
    result.gapChars = quality.gapChars
    result.gapPct = quality.gapPct
  }
  return result
}

/** Strip ```json … ``` fences that some models add despite instructions. */
export function stripCodeFence(raw: string): string {
  const s = String(raw ?? '').trim()
  if (!s) return s
  const fenced = s.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (fenced && fenced[1]) return fenced[1].trim()
  return s
}

/* ═══════════════════ Persistence ═══════════════════ */

export async function persist(userId: number, dossier: StoryDossier): Promise<void> {
  await ensureDir(userId)
  const file = dossierFile(userId, dossier.scriptId)
  await fs.writeFile(file, JSON.stringify(dossier, null, 2), 'utf-8')
  memoryCache.set(cacheKey(userId, dossier.scriptId), { loadedAt: Date.now(), dossier })
}

export async function deleteDossier(userId: number, scriptId: string): Promise<boolean> {
  memoryCache.delete(cacheKey(userId, scriptId))
  await deleteAnnex(userId, scriptId)
  await deleteGaps(userId, scriptId)
  try {
    await fs.unlink(dossierFile(userId, scriptId))
    return true
  } catch {
    return false
  }
}

/** Load a dossier from disk (cached). null when missing/unparsable. */
export async function loadDossier(userId: number, scriptId: string): Promise<StoryDossier | null> {
  const key = cacheKey(userId, scriptId)
  const hit = memoryCache.get(key)
  if (hit && Date.now() - hit.loadedAt < CACHE_TTL_MS) return hit.dossier
  try {
    const raw = await fs.readFile(dossierFile(userId, scriptId), 'utf-8')
    const dossier = parseDossierJson(raw)
    if (dossier) {
      memoryCache.set(key, { loadedAt: Date.now(), dossier })
      return dossier
    }
  } catch {
    // missing file → null
  }
  return null
}

/** Synchronous cache-only read (for handlers that cannot await). */
export function peekDossier(userId: number, scriptId: string): StoryDossier | null {
  return memoryCache.get(cacheKey(userId, scriptId))?.dossier ?? null
}

/** 档案清单条目（#55：带生成期质量视图，故事列表/开局门闩据此判定降质）。 */
export interface DossierListItem {
  scriptId: string
  name: string
  sceneCount: number
  generatedAt: number
  /** sceneText 覆盖率（%）：快照直读；旧档案由 .gaps.json 兄弟文件估算。 */
  coveragePct?: number
  /** 降质标记：快照 degraded，或旧档案估算覆盖 < DOSSIER_MIN_COVERAGE_PCT。 */
  degraded?: boolean
  /** 快照中的分节失败数（旧档案估算路径无此值）。 */
  failedBatches?: number
}

/** List a user's generated dossiers (disk scan). */
export async function listDossiers(userId: number): Promise<DossierListItem[]> {
  let entries: string[]
  try {
    entries = await fs.readdir(userDir(userId))
  } catch {
    return []
  }
  const out: DossierListItem[] = []
  for (const f of entries) {
    if (!f.endsWith('.json')) continue
    try {
      const raw = await fs.readFile(path.join(userDir(userId), f), 'utf-8')
      const d = parseDossierJson(raw)
      if (!d) continue
      const item: DossierListItem = {
        scriptId: d.scriptId,
        name: d.storyName,
        sceneCount: d.scenes.length,
        generatedAt: d.generatedAt,
        coveragePct: d.quality?.coveragePct,
        degraded: d.quality?.degraded,
        failedBatches: d.quality?.failedBatches,
      }
      if (d.quality === undefined) {
        // 旧档案（quality 快照引入前）：读同目录兄弟 .gaps.json 估算覆盖。
        // 兄弟文件名源自 readdir 磁盘清单（非请求输入），不引入 keyed fs 读。
        const est = await estimateLegacyCoverage(userDir(userId), f)
        if (est !== undefined) {
          item.coveragePct = est
          item.degraded = est < DOSSIER_MIN_COVERAGE_PCT
        }
      }
      out.push(item)
    } catch {
      // skip unparsable files
    }
  }
  return out.sort((a, b) => b.generatedAt - a.generatedAt)
}

/** 旧档案覆盖估算：兄弟 .gaps.json 的缺口比（100 - gapPct）。仅信当前算法版本
 *  （v1 的 gapPct 系统性偏高，宁放行不误伤）；无明细/损坏 → undefined（不判定）。 */
async function estimateLegacyCoverage(dir: string, dossierFileName: string): Promise<number | undefined> {
  try {
    const gapsPath = path.join(dir, `${dossierFileName.slice(0, -'.json'.length)}.gaps.json`)
    const gaps = JSON.parse(await fs.readFile(gapsPath, 'utf-8')) as { storyChars?: number; gapPct?: number; gapsVersion?: number } | null
    if (!gaps || typeof gaps.storyChars !== 'number' || typeof gaps.gapPct !== 'number') return undefined
    if ((gaps.gapsVersion ?? 1) < GAPS_VERSION) return undefined
    if (gaps.storyChars <= 5_000) return undefined // 小剧本不判降质（与快照口径一致）
    return Math.round((100 - gaps.gapPct) * 10) / 10
  } catch {
    return undefined
  }
}

/* ═══════════════════ 质量门提示（#55 产物期） ═══════════════════ */

/** 降质档案的开局拒绝文案（单源：startRoom / createSoloRoom 经 dossierGateNotice
 *  共用，与「尚未生成档案」的 409 严格分开——缺档案指引生成，残档指引重生成）。 */
function dossierDegradedNoticeText(q: { coveragePct?: number; failedBatches?: number }): string {
  const bits: string[] = []
  if (typeof q.coveragePct === 'number') bits.push(`sceneText 覆盖率仅 ${q.coveragePct}%`)
  if (q.failedBatches) bits.push(`${q.failedBatches} 个分节解析失败`)
  return (
    `档案质量不足（${bits.join('；') || '低覆盖'}）——残档会让 KP 反复查证空转、游玩体验明显变差。` +
    `建议在「我的故事」中重新生成档案后再开局。`
  )
}

/**
 * #55 开局门闩降质判定（**纯函数**）：档案清单里该剧本的降质提示，null = 放行。
 * 输入来自 listDossiers 磁盘扫描（文件名源自 readdir，非请求输入）——门闩的
 * REST 可达链上不出现"以请求 id 为键"的 fs 读；缺档案与无质量数据的旧档案
 * 返回 null（「未生成」由各门闩的既有分支提示，不是降质）。
 */
export function dossierGateNotice(items: DossierListItem[], scriptId: string): string | null {
  const hit = items.find((d) => d.scriptId === scriptId)
  if (!hit || hit.degraded === undefined) return null
  return hit.degraded
    ? dossierDegradedNoticeText({ coveragePct: hit.coveragePct, failedBatches: hit.failedBatches })
    : null
}

/* ═══════════════════ Lookups ═══════════════════ */

export function listScenes(dossier: StoryDossier): { id: string; name: string; description?: string }[] {
  return (dossier.scenes || []).map((s) => ({ id: s.id, name: s.name, description: s.description }))
}

/** 档案落空/覆盖不足时指向查证工具的引导句（单源：三个渲染函数共用）。 */
export const VERIFY_ORIGINAL_HINT = '可用 verify_original 在剧本原文中查证'

/** 覆盖提示行（P26）：仅在"确有缺口"时出声——覆盖完整的场景不打扰 KP。 */
export function coverageHintLine(coverage: SceneCoverage | null | undefined): string {
  if (!coverage || coverage.gapCount <= 0) return ''
  return `原文收录：约 ${coverage.coveragePct}%（另有 ${coverage.gapCount} 段未收录）——需要原文级细节时${VERIFY_ORIGINAL_HINT}，不要凭印象补全。`
}

/** Render a scene's static dossier block (used by buildDossierContext).
 *  传入 coverage 时附一行覆盖提示（P26：让 KP 知道块内可能缺东西）。 */
export function buildSceneBlock(dossier: StoryDossier, sceneNameOrId: string, coverage?: SceneCoverage | null): string {
  const scene = findScene(dossier, sceneNameOrId)
  if (!scene) return ''
  const lines: string[] = []
  lines.push(`场景：${scene.name}`)
  if (scene.description) lines.push(`简介：${scene.description}`)
  if (scene.sceneText) lines.push(`现场描述：\n${scene.sceneText}`)
  if (scene.npcIds?.length) {
    const npcs = (scene.npcIds || [])
      .map((id) => dossier.npcs.find((n) => n.id === id))
      .filter((n): n is StoryDossier['npcs'][number] => !!n)
    if (npcs.length) lines.push(`在场 NPC：${npcs.map((n) => `${n.name}（${n.role ?? '身份不明'}）${n.description ? `：${n.description}` : ''}`).join('；')}`)
  }
  if (scene.hooks?.length) lines.push(`可推进的行动：${scene.hooks.join('；')}`)
  if (scene.clueIds?.length) {
    const clues = (scene.clueIds || [])
      .map((id) => dossier.clues.find((c) => c.id === id))
      .filter((c): c is StoryDossier['clues'][number] => !!c)
    if (clues.length) lines.push(`本场景可获得线索：${clues.map((c) => c.description).join('；')}`)
  }
  const hint = coverageHintLine(coverage)
  if (hint) lines.push(hint)
  return lines.join('\n')
}

/* 查档案落空时的回包文案（P26）：把"档案没有"显式导向原文查证工具——
 * P25 观测到 KP 以档案为完整真源，落空时会直接放弃或凭印象作答。 */

export function renderSceneNotFound(sceneName: string, sceneNames: string[]): string {
  return `剧本中没有「${sceneName}」。可前往的场景：${sceneNames.join('、') || '（无）'}。档案可能不全——${VERIFY_ORIGINAL_HINT}。`
}

export function renderLexicalMiss(query: string): string {
  return `剧本档案中未找到与「${query}」相关的内容。档案可能不全——${VERIFY_ORIGINAL_HINT}。`
}

/* 房间所报场景与档案对不上时的回包文案（#53）：**不**拿别的场景块顶上。
 * 与 renderSceneNotFound 的区别在"谁报错了"——那条是工具查询的名字没命中，
 * 这条是房间场景（KP transition_scene 自由命名）与档案不一致；诊断指向也不同：
 * 先让 KP 用 transition_scene 把场景名纠正到档案口径，再留查证出口。
 * 两条共用同一句引导。
 * ⚠️ 首行的 `【场景归属提示】` 标记是**必需的**：该文本被塞进 `## 当前场景档案`
 * 标题下，而提示词又说那里是"当前所在场景的权威描述"（kpPromptService）——
 * 没有醒目标记时，"未覆盖"会被读成"这就是当前场景的档案"。 */

export function renderSceneUncovered(sceneName: string, sceneNames: string[]): string {
  const name = String(sceneName ?? '').trim()
  if (!name) return ''
  return (
    `【场景归属提示】档案未覆盖当前场景「${name}」。档案中的场景：${sceneNames.join('、') || '（无）'}。` +
    `不要按别的场景推测当前状况——若确认当前实际位于档案中的某场景，用 transition_scene 以档案里的写法更正场景名；` +
    `也可用 scene_list 查看场景清单。需要原文级细节时${VERIFY_ORIGINAL_HINT}。`
  )
}

/**
 * Case-insensitive scene lookup by id/name/exact/contains (longest match wins).
 * 实现单源在 `./sceneLookup.js`（纯函数轻模块）——查询期模块只为这一个查找
 * 不该被本文件的重依赖链牵连。下方 re-export 保持既有调用方的导入路径不变。
 */
export function findScene(dossier: StoryDossier, nameOrId: string): StoryDossier['scenes'][number] | null {
  return findSceneImpl(dossier, nameOrId)
}

/** Lightweight lexical search over scenes/clues/npcs (shared tool primitive). */
export function lexicalSearch(
  dossier: StoryDossier,
  query: string,
  topK: number = 5,
): { kind: 'scene' | 'clue' | 'npc'; name: string; text: string; score: number }[] {
  const q = tokenize(String(query ?? ''))
  if (q.length === 0) return []
  const hits: { kind: 'scene' | 'clue' | 'npc'; name: string; text: string; score: number }[] = []
  for (const s of dossier.scenes || []) {
    const score = scoreText([s.name, s.description, s.sceneText, (s.keywords || []).join(' ')].filter(Boolean).join(' '), q)
    if (score > 0) hits.push({ kind: 'scene', name: s.name, text: s.sceneText.slice(0, 400) || s.description || '', score })
  }
  for (const c of dossier.clues || []) {
    const score = scoreText([c.description, c.location || ''].join(' '), q)
    if (score > 0) hits.push({ kind: 'clue', name: c.description.slice(0, 30), text: c.description, score })
  }
  for (const n of dossier.npcs || []) {
    const score = scoreText([n.name, n.role || '', n.description || '', n.details || ''].join(' '), q)
    if (score > 0) hits.push({ kind: 'npc', name: n.name, text: n.details || n.description || '', score })
  }
  return hits.sort((a, b) => b.score - a.score).slice(0, topK)
}

/** Tokenize Chinese text: CJK chars as unigrams + latin words. */
function tokenize(text: string): string[] {
  const s = String(text ?? '').toLowerCase()
  const cjk = s.match(/[\u4e00-\u9fff]/g) || []
  const words = s.match(/[a-z0-9]+/g) || []
  return [...cjk, ...words].filter((t) => t.length > 0)
}

function scoreText(text: string, queryTerms: string[]): number {
  const body = tokenize(text)
  if (body.length === 0) return 0
  let score = 0
  for (const t of queryTerms) {
    if (body.includes(t)) score += 1
  }
  return score
}
