/**
 * Story dossier service — the dossier workflow's persistence + query core.
 *
 * A dossier is a structured story digest (scenes/clues/npcs with machine-
 * readable gates + per-scene narrative text) pre-generated by an LLM from the
 * full story text, replacing per-turn embedding retrieval for dossier rooms.
 *
 * Responsibilities:
 *  - generate(userId, story): read the story, batch it, call the LLM per batch,
 *    parse + merge into one StoryDossier, persist to DOSSIER_DATA_DIR/<uid>/.
 *  - load/get: TTL-cached reads (mirrors graphStore memory cache pattern).
 *  - query: the dossier workflow's lookups used by the turn pipeline and the
 *    story-lookup tools — listScenes / getSceneBlock (static per-scene text) /
 *    lexicalSearch (tokenized term overlap).
 *
 * The chat path goes through `chatForRag` (aiService) so it inherits protocol
 * dispatch + URL safety + the MOCK_AI script. In MOCK_AI mode the script
 * returns deterministic JSON for dossier prompts (see mockAi.ts), so e2e can
 * run the whole dossier flow without an LLM.
 *
 * Path safety: every fs path is built from a sanitized script id AND checked
 * against the per-user dossier root via resolveFileInDir (utils/pathSafety).
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { DOSSIER_DATA_DIR } from '../../config.js'
import { readStoryForRag, readStory } from '../../services/storyService.js'
import { chatForRag } from '../../services/aiService.js'
import { resolveFileInDir } from '../../utils/pathSafety.js'
import {
  DOSSIER_BATCH_CHARS,
  DOSSIER_SYSTEM_PROMPT,
  buildDossierPrompt,
  mergeDossierParts,
} from './prompts.js'
import {
  parseDossierJson,
  sanitizeScriptId,
  type StoryDossier,
} from './schema.js'

/** TTL for in-memory dossier cache (ms). */
const CACHE_TTL_MS = 60_000
/** Max raw story chars fed to the generator overall (safety; ~170k max known). */
const MAX_GENERATE_CHARS = 200_000
/** Max generation batches per story (safety). */
const MAX_BATCHES = 24

export interface GenerateResult {
  ok: boolean
  scriptId?: string
  scenes?: number
  clues?: number
  npcs?: number
  error?: string
}

const memoryCache = new Map<string, { loadedAt: number; dossier: StoryDossier }>()

function cacheKey(userId: number, scriptId: string): string {
  return `${userId}:${scriptId}`
}

/** Per-user dossier dir (never built from the raw script id). */
function userDir(userId: number): string {
  return path.join(DOSSIER_DATA_DIR, String(userId))
}

/** Resolve a script id to a file path inside the user dir (sanitize + boundary check). */
function dossierFile(userId: number, scriptId: string): string {
  const fileName = `${sanitizeScriptId(scriptId)}.json`
  return resolveFileInDir(userDir(userId), fileName, 'dossier file')
}

async function ensureDir(userId: number): Promise<string> {
  await fs.mkdir(userDir(userId), { recursive: true })
  return userDir(userId)
}

/* ═══════════════════ Generation ═══════════════════ */

/** Split raw story text into sequential sections for batched LLM extraction. */
export function splitStorySections(content: string, batchChars: number = DOSSIER_BATCH_CHARS): string[] {
  const text = String(content ?? '').trim()
  if (!text) return []
  if (text.length <= batchChars) return [text]
  const sections: string[] = []
  let rest = text
  // Prefer splitting at markdown-ish headings / blank-line paragraph gaps.
  while (rest.length > batchChars) {
    const head = rest.slice(0, batchChars)
    const lastBreak = Math.max(head.lastIndexOf('\n\n'), head.lastIndexOf('\n#'), head.lastIndexOf('\n##'), head.lastIndexOf('\n###'))
    const cutAt = lastBreak >= batchChars * 0.5 ? lastBreak : head.length
    sections.push(rest.slice(0, cutAt).trim())
    rest = rest.slice(cutAt).trim()
  }
  if (rest) sections.push(rest)
  return sections
}

/**
 * Generate a dossier for a user's story. `model` overrides settings (mirrors
 * graphStore.indexGraph's extractionModel param). Reads the story text via
 * readStoryForRag (PDF → parsePdfWithOcr). Batches long stories; feeds
 * previously-seen names back for cross-batch consistency.
 */
export async function generateDossier(
  userId: number,
  scriptId: string,
  options: { model?: string } = {},
): Promise<GenerateResult> {
  const { model } = options
  if (!scriptId) return { ok: false, error: 'missing scriptId' }

  let raw: { name: string; content: string }
  try {
    raw = await readStoryForRag(userId, scriptId)
  } catch {
    // Fall back to the plain read for txt/md (no OCR needed).
    try {
      raw = await readStory(userId, scriptId)
    } catch {
      return { ok: false, error: 'story not found' }
    }
  }
  const content = (raw?.content || '').trim()
  if (!content) return { ok: false, error: 'story content is empty' }

  const storyText = content.slice(0, MAX_GENERATE_CHARS)
  const sections = splitStorySections(storyText)
  const batches = sections.slice(0, MAX_BATCHES)
  const totalBatches = batches.length

  const seenSceneNames: string[] = []
  const seenNpcNames: string[] = []
  const seenClueDescriptions: string[] = []
  const parsedParts: StoryDossier[] = []
  let lastError = ''

  for (let bi = 0; bi < totalBatches; bi++) {
    const prompt = buildDossierPrompt({
      batchIndex: bi,
      storyText: batches[bi],
      seenSceneNames,
      seenNpcNames,
      seenClueDescriptions,
    })
    try {
      const res = await chatForRag(userId, {
        messages: [
          { role: 'system', content: DOSSIER_SYSTEM_PROMPT },
          { role: 'user', content: prompt },
        ],
        temperature: 0,
        maxTokens: 4096,
        model,
      })
      const parsed = parseDossierJson(stripCodeFence(res?.content || ''))
      if (parsed && parsed.scenes.length + parsed.clues.length + parsed.npcs.length > 0) {
        parsedParts.push({
          ...parsed,
          scriptId: parsed.scriptId || scriptId,
          storyName: parsed.storyName || raw.name || scriptId,
          generatedByModel: parsed.generatedByModel || model,
        })
        for (const s of parsed.scenes) if (s.name && !seenSceneNames.includes(s.name)) seenSceneNames.push(s.name)
        for (const n of parsed.npcs) if (n.name && !seenNpcNames.includes(n.name)) seenNpcNames.push(n.name)
        for (const c of parsed.clues) if (c.description && !seenClueDescriptions.includes(c.description)) seenClueDescriptions.push(c.description)
      } else {
        lastError = `batch ${bi + 1}/${totalBatches}: 解析结果为空`
      }
    } catch (e) {
      lastError = `batch ${bi + 1}/${totalBatches}: ${e instanceof Error ? e.message : String(e)}`
    }
  }

  if (parsedParts.length === 0) {
    return { ok: false, error: lastError || 'dossier generation failed' }
  }

  const merged = mergeDossierParts(parsedParts)
  const dossier: StoryDossier = {
    ...merged,
    scriptId,
    storyName: merged.storyName || raw.name || scriptId,
    generatedAt: Date.now(),
    generatedByModel: merged.generatedByModel || model,
  }

  await persist(userId, dossier)
  return {
    ok: true,
    scriptId,
    scenes: dossier.scenes.length,
    clues: dossier.clues.length,
    npcs: dossier.npcs.length,
  }
}

/** Strip ```json … ``` fences that some models add despite instructions. */
export function stripCodeFence(raw: string): string {
  const s = String(raw ?? '').trim()
  if (!s) return s
  const fenced = s.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (fenced && fenced[1]) return fenced[1].trim()
  return s
}

/* ═══════════════════ Persistence ═══════════════════ */

export async function persist(userId: number, dossier: StoryDossier): Promise<void> {
  await ensureDir(userId)
  const file = dossierFile(userId, dossier.scriptId)
  await fs.writeFile(file, JSON.stringify(dossier, null, 2), 'utf-8')
  memoryCache.set(cacheKey(userId, dossier.scriptId), { loadedAt: Date.now(), dossier })
}

export async function deleteDossier(userId: number, scriptId: string): Promise<boolean> {
  memoryCache.delete(cacheKey(userId, scriptId))
  try {
    await fs.unlink(dossierFile(userId, scriptId))
    return true
  } catch {
    return false
  }
}

/** Load a dossier from disk (cached). null when missing/unparsable. */
export async function loadDossier(userId: number, scriptId: string): Promise<StoryDossier | null> {
  const key = cacheKey(userId, scriptId)
  const hit = memoryCache.get(key)
  if (hit && Date.now() - hit.loadedAt < CACHE_TTL_MS) return hit.dossier
  try {
    const raw = await fs.readFile(dossierFile(userId, scriptId), 'utf-8')
    const dossier = parseDossierJson(raw)
    if (dossier) {
      memoryCache.set(key, { loadedAt: Date.now(), dossier })
      return dossier
    }
  } catch {
    // missing file → null
  }
  return null
}

/** Synchronous cache-only read (for handlers that cannot await). */
export function peekDossier(userId: number, scriptId: string): StoryDossier | null {
  return memoryCache.get(cacheKey(userId, scriptId))?.dossier ?? null
}

/** List a user's generated dossiers (disk scan). */
export async function listDossiers(userId: number): Promise<{ scriptId: string; name: string; sceneCount: number; generatedAt: number }[]> {
  let entries: string[]
  try {
    entries = await fs.readdir(userDir(userId))
  } catch {
    return []
  }
  const out: { scriptId: string; name: string; sceneCount: number; generatedAt: number }[] = []
  for (const f of entries) {
    if (!f.endsWith('.json')) continue
    try {
      const raw = await fs.readFile(path.join(userDir(userId), f), 'utf-8')
      const d = parseDossierJson(raw)
      if (d) out.push({ scriptId: d.scriptId, name: d.storyName, sceneCount: d.scenes.length, generatedAt: d.generatedAt })
    } catch {
      // skip unparsable files
    }
  }
  return out.sort((a, b) => b.generatedAt - a.generatedAt)
}

/* ═══════════════════ Lookups ═══════════════════ */

export function listScenes(dossier: StoryDossier): { id: string; name: string; description?: string }[] {
  return (dossier.scenes || []).map((s) => ({ id: s.id, name: s.name, description: s.description }))
}

/** Render a scene's static dossier block (used by buildDossierContext). */
export function buildSceneBlock(dossier: StoryDossier, sceneNameOrId: string): string {
  const scene = findScene(dossier, sceneNameOrId)
  if (!scene) return ''
  const lines: string[] = []
  lines.push(`场景：${scene.name}`)
  if (scene.description) lines.push(`简介：${scene.description}`)
  if (scene.sceneText) lines.push(`现场描述：\n${scene.sceneText}`)
  if (scene.npcIds?.length) {
    const npcs = (scene.npcIds || [])
      .map((id) => dossier.npcs.find((n) => n.id === id))
      .filter((n): n is StoryDossier['npcs'][number] => !!n)
    if (npcs.length) lines.push(`在场 NPC：${npcs.map((n) => `${n.name}（${n.role ?? '身份不明'}）${n.description ? `：${n.description}` : ''}`).join('；')}`)
  }
  if (scene.hooks?.length) lines.push(`可推进的行动：${scene.hooks.join('；')}`)
  if (scene.clueIds?.length) {
    const clues = (scene.clueIds || [])
      .map((id) => dossier.clues.find((c) => c.id === id))
      .filter((c): c is StoryDossier['clues'][number] => !!c)
    if (clues.length) lines.push(`本场景可获得线索：${clues.map((c) => c.description).join('；')}`)
  }
  return lines.join('\n')
}

/** Case-insensitive scene lookup by id/name/exact/contains (longest match wins). */
export function findScene(dossier: StoryDossier, nameOrId: string): StoryDossier['scenes'][number] | null {
  const target = String(nameOrId || '').trim().toLowerCase()
  if (!target) return null
  const scenes = dossier.scenes || []
  for (const s of scenes) {
    if (s.id.toLowerCase() === target || s.name.toLowerCase() === target) return s
  }
  let best: StoryDossier['scenes'][number] | null = null
  let bestLen = 0
  for (const s of scenes) {
    const name = s.name.toLowerCase()
    if (name && target.includes(name) && name.length > bestLen) {
      best = s
      bestLen = name.length
    }
  }
  return best
}

/** Lightweight lexical search over scenes/clues/npcs (shared tool primitive). */
export function lexicalSearch(
  dossier: StoryDossier,
  query: string,
  topK: number = 5,
): { kind: 'scene' | 'clue' | 'npc'; name: string; text: string; score: number }[] {
  const q = tokenize(String(query ?? ''))
  if (q.length === 0) return []
  const hits: { kind: 'scene' | 'clue' | 'npc'; name: string; text: string; score: number }[] = []
  for (const s of dossier.scenes || []) {
    const score = scoreText([s.name, s.description, s.sceneText, (s.keywords || []).join(' ')].filter(Boolean).join(' '), q)
    if (score > 0) hits.push({ kind: 'scene', name: s.name, text: s.sceneText.slice(0, 400) || s.description || '', score })
  }
  for (const c of dossier.clues || []) {
    const score = scoreText([c.description, c.location || ''].join(' '), q)
    if (score > 0) hits.push({ kind: 'clue', name: c.description.slice(0, 30), text: c.description, score })
  }
  for (const n of dossier.npcs || []) {
    const score = scoreText([n.name, n.role || '', n.description || '', n.details || ''].join(' '), q)
    if (score > 0) hits.push({ kind: 'npc', name: n.name, text: n.details || n.description || '', score })
  }
  return hits.sort((a, b) => b.score - a.score).slice(0, topK)
}

/** Tokenize Chinese text: CJK chars as unigrams + latin words. */
function tokenize(text: string): string[] {
  const s = String(text ?? '').toLowerCase()
  const cjk = s.match(/[\u4e00-\u9fff]/g) || []
  const words = s.match(/[a-z0-9]+/g) || []
  return [...cjk, ...words].filter((t) => t.length > 0)
}

function scoreText(text: string, queryTerms: string[]): number {
  const body = tokenize(text)
  if (body.length === 0) return 0
  let score = 0
  for (const t of queryTerms) {
    if (body.includes(t)) score += 1
  }
  return score
}
